### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by Frontrider** [enlivenapp/Open-Blog#5]
To check the admin panel, I needed to remove permission checks, I can not log in with the password set in the install process. (working on it)

**Comment by enlivenapp** [comment]
Is this the same report as #4 ?

**Comment by Frontrider** [comment]
Okey, screwed up, they were intended for v3, I have no idea how I ended up here.

**Comment by enlivenapp** [comment]
no problem.  Thanks for posting them in the v3 repo.  I'm working on bug fixes today.
